### PR TITLE
Test tab out of editor scenarios

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Try to make the existing focus tests simpler to follow. 
Create a method to assert focus that we can use to create more such assertions.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Latest failure was in the CF invalidation. Re-running.

**Comment by microbit-matt-hillsdon** [comment]
Passed this time but queuing again for confirmation as I hit various flakiness when writing (though not with the latest code).

**Comment by microbit-matt-hillsdon** [comment]
> Passed this time but queuing again for confirmation as I hit various flakiness when writing (though not with the latest code).

All looks good.

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Pull request merged**
