### PR TITLE
Migrate from CircleCI to GitHub actions

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Not keeping CircleCI build as there's value in the move to GitHub actions for open source contributions.

Having said that, I've focussed on getting our deployment up and running and there's no PR trigger yet.

Steps require internal GH packages for deployment, but these should be easy to factor out. I'd like forks to be able to at least run e2e and perhaps in time add a template for GH pages deploys.

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
Environment looks good so I'll re-enable the deploy steps:

```
STAGE: REVIEW
REACT_APP_STAGE: REVIEW
PUBLIC_URL: /gh-actions/
E2E_PUBLIC_URL: /gh-actions/
```

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Comment by microbit-matt-hillsdon** [comment]
I merged this and monitored the first run.
STAGE was set correctly but PUBLIC_URL was incorrectly set to /main/ so I cancelled the build. I'll look further shortly.

**Comment by microbit-matt-hillsdon** [comment]
> I merged this and monitored the first run. STAGE was set correctly but PUBLIC_URL was incorrectly set to /main/ so I cancelled the build. I'll look further shortly.

This was fixed by https://github.com/microbit-foundation/python-editor-v3/pull/1088 and the current beta deployment is now from GHA.

**Pull request merged**
